export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const SWITCH_THEME = 'SWITCH_THEME'
export const CHANGE_LANG = 'CHANGE_LANG'
export const GET_USER = 'GET_USER'
export const MENU_TABLE = 'MENU_TABLE'
export const NAME_TABLE = 'NAME_TABLE'